name:                Halt
version:             0.1.0.0
github:              "dignissimus/Halt"
license:             BSD3
author:              "Sam Ezeh"
maintainer:          "sam.z.ezeh@gmail.com"
copyright:           "2021 Sam Ezeh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Halt#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Halt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Halt

tests:
  Halt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Halt
